parameters:
#    brainstrap_user.example.class: Brainstrap\UserBundle\Example

services:
#    brainstrap_user.example:
#        class: %brainstrap_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    brainstrap_user.registration.form.type:
        class: Brainstrap\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: brainstrap_user_registration }

    brainstrap_user.profile.form.type:
        class: Brainstrap\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: brainstrap_user_profile }