service:
    path:     /
    defaults: { _controller: "BrainstrapUserBundle:Service:index" }

service_show:
    path:     /{id}/show
    defaults: { _controller: "BrainstrapUserBundle:Service:show" }

service_new:
    path:     /new
    defaults: { _controller: "BrainstrapUserBundle:Service:new" }

service_create:
    path:     /create
    defaults: { _controller: "BrainstrapUserBundle:Service:create" }
    requirements: { _method: post }

service_edit:
    path:     /{id}/edit
    defaults: { _controller: "BrainstrapUserBundle:Service:edit" }

service_update:
    path:     /{id}/update
    defaults: { _controller: "BrainstrapUserBundle:Service:update" }
    requirements: { _method: post|put }

service_delete:
    path:     /{id}/delete
    defaults: { _controller: "BrainstrapUserBundle:Service:delete" }
    requirements: { _method: post|delete }
